name: Blog CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        gitUsername: [infiWang]
        gitUserEmail: [root@infi.wang]
        nodeVersion: [12.x]
    
    steps:
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    
    - name: Setup git env
      run: |
        git config --global user.name '${{ matrix.gitUsername }}'
        git config --global user.email '${{ matrix.gitUserEmail }}'
        
    - name: Checkout Base
      uses: actions/checkout@v2
    
    - name: Checkout Submodules
      run: |
        echo ${{ secrets.sshVolantisThemePulling }} > ~/.ssh/id_ecdsa
        chmod 600 ~/.ssh/id_ecdsa
        git submodule update --init --recursive --force
        rm ~/.ssh/id_ecdsa
    
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodeVersion }}
    
    - name: Install yarn, Hexo and nodejs packages
      run: |
        npm i yarn -g
        yarn global add hexo-cli
        yarn install
        
    - name: Pull history files
      run: |
        git clone --branch=master https://github.com/infiWang/infiWang.github.io.git .deploy_git

    - name: Generate and Deploy
      run: |
        echo ${{ secrets.sshCiGithubPages }} > ~/.ssh/id_ecdsa
        chmod 600 ~/.ssh/id_ecdsa
        hexo g -d
        rm ~/.ssh/id_ecdsa

    - name: Cloudflare Purge Cache
      uses: jakejarvis/cloudflare-purge-action@v0.3.0
      env:
        CLOUDFLARE_ZONE: ${{ secrets.actionCloudflareZoneID }}
        CLOUDFLARE_TOKEN: ${{ secrets.actionCloudflareToken }}
