name: Blog CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        gitUsername: [infiWang]
        gitUserEmail: [root@infi.wang]
        nodeVersion: [12.x]
    
    steps:
    - name: Setup git env
      env:
        ACTION_KEY: ${{ secrets.actionKey }}
      run: |
        mkdir -p ~/.ssh/
        echo "$ACTION_KEY" >> ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name '${{ matrix.gitUsername }}'
        git config --global user.email '${{ matrix.gitUserEmail }}'
        
    - name: Checkout Base
      uses: actions/checkout@v2
    
    - name: Checkout Submodules
      run: |
        git submodule update --init --recursive --force
    
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodeVersion }}
    
    - name: Install Hexo and npm dependencies
      run: |
        npm i -g hexo-cli
        npm install
  
    - name: Pull history files
      run: |
        git clone --depth 1 --branch=master https://github.com/infiWang/infiWang.github.io.git .deploy_git
        cd .deploy_git
        find . -path ./.git -prune -o -exec rm -rf {} \;
        cd ..
  
    - name: Generate and Deploy
      run: |
        hexo g -d

    - name: Cloudflare Purge Cache
      uses: jakejarvis/cloudflare-purge-action@v0.3.0
      env:
        CLOUDFLARE_ZONE: ${{ secrets.actionCloudflareZoneID }}
        CLOUDFLARE_TOKEN: ${{ secrets.actionCloudflareToken }}
