name: Blog CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        gitUsername: [infiWang]
        gitUserEmail: [root@infi.wang]
        nodeVersion: [12.x]
    
    steps:
    - name: Install Github.io Deploy SSH key
      uses: webfactory/ssh-agent@v0.2.0
      with: 
        ssh-private-key: |
          ${{ secrets.sshCiGithubPages }}
          ${{ secrets.sshVolantisThemePulling }}
    
    - name: Setup git env
      env:
        ACTION_KEY: ${{ secrets.sshCiGithubPages }}
      run: |
        git config --global user.name '${{ matrix.gitUsername }}'
        git config --global user.email '${{ matrix.gitUserEmail }}'
        
    - name: Checkout Base
      uses: actions/checkout@v2
    
    - name: Checkout Submodules
      run: |
        git submodule update --init --recursive --force
    
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodeVersion }}
    
    - name: Install yarn, Hexo and nodejs packages
      run: |
        npm i yarn -g
        yarn global add hexo-cli
        yarn install
        
    - name: Pull history files
      run: |
        git clone --branch=master https://github.com/infiWang/infiWang.github.io.git .deploy_git

    - name: Generate and Deploy
      run: |
        hexo g -d

    - name: Cloudflare Purge Cache
      uses: jakejarvis/cloudflare-purge-action@v0.3.0
      env:
        CLOUDFLARE_ZONE: ${{ secrets.actionCloudflareZoneID }}
        CLOUDFLARE_TOKEN: ${{ secrets.actionCloudflareToken }}
