name: Deploy Blog

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        nodeVersion: [12.x]
    
    steps:
    - name: Setup git env
      env:
        ACTION_KEY: ${{ secrets.actionKey }}
      run: |
        mkdir -p ~/.ssh/
        echo "$ACTION_KEY" >> ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name 'infiWang'
        git config --global user.email 'root@infi.wang'
        
    - name: Checkout Base
      uses: actions/checkout@v2
    
    - name: Checkout Submodules
      run: |
        git submodule update --init --recursive --force
    
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodeVersion }}
    
    - name: Install Hexo and npm dependencies
      run: |
        npm i -g hexo-cli
        npm install
  
    - name: Deploy
      run: |
        hexo g -d
