name: Deploy Blog

on: [push] # 当有新push时运行

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    
    - name: Setup git env
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name 'infiWang'
        git config --global user.email 'root@infi.wang'
    - name: Install Hexo and npm dependencies
      run: |
        npm i -g hexo-cli
        npm install
  
    - name: Deploy
      run: |
        hexo clean && hexo generate -d
